name: Deploy and build content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
concurrency:
  group: github-pages
  cancel-in-progress: false
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  actions: read
  pages: write
  id-token: write
  
jobs:
  build:

    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    strategy:
      matrix:
        node-version: [ 18, 20 ]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: install and test
      run: |
        npm install -g yarn
        npm install -g gulp
        yarn install
        gulp build # to do: we should make this run by `npm test`
    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.6
      with:
        # Upload entire repository
        path: 'build'
        overwrite: true
        name: github-pages
    - name: Deploy to GH Pages 🚀
      uses: actions/deploy-pages@v4.0.5
      with:
        artifact_name: github-pages
